# Generated by Django 4.2.9 on 2024-01-13 02:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_organizador', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Generos',
            new_name='Autor',
        ),
        migrations.RenameModel(
            old_name='Autores',
            new_name='Genero',
        ),
        migrations.RenameModel(
            old_name='Libros',
            new_name='Libro',
        ),
    ]
