# Generated by Django 4.2.9 on 2024-01-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizador', '0003_remove_libro_genero_nombre_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='anio_publicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
