# Generated by Django 4.2.9 on 2024-01-16 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_organizador', '0006_rename_comentario_comentario_texto_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='libro',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='app_organizador.libro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
